export interface Restaurant {
  name: string
  city: 'Dallas' | 'Austin'
  category: string
  area: string
  note: string
  price: number
  rating: number
  reviews: number
  url: string | null
  mapsQuery: string
  recommended: boolean
  isNew: boolean
  lat: number
  lng: number
}

export const RESTAURANTS: Restaurant[] = [
  // DALLAS
  { name: "Afrah Mediterranean", city: "Dallas", category: "Lebanese", area: "Richardson", note: "Most reviewed Med in DFW, lunch buffet, pita bakery", price: 2, rating: 4.2, reviews: 5291, url: "https://afrahrestaurant.com", mapsQuery: "Afrah+Mediterranean+Restaurant+Richardson+TX", recommended: true, isNew: false, lat: 32.9486, lng: -96.7298 },
  { name: "The Mayor's House by Selda", city: "Dallas", category: "Turkish", area: "Oak Cliff", note: "Most reviewed Turkish in DFW, historic house", price: 2, rating: 4.8, reviews: 3230, url: "https://themayorshousebyselda.com", mapsQuery: "The+Mayors+House+by+Selda+Dallas+TX", recommended: true, isNew: false, lat: 32.7245, lng: -96.8315 },
  { name: "Fadi's Mediterranean Grill", city: "Dallas", category: "Lebanese", area: "Knox-Henderson", note: "Fast casual cafeteria line, great sides", price: 2, rating: 4.3, reviews: 2215, url: "http://fadiscuisine.com", mapsQuery: "Fadis+Mediterranean+Grill+Dallas+TX", recommended: true, isNew: false, lat: 32.8218, lng: -96.7869 },
  { name: "Selda Mediterranean", city: "Dallas", category: "Turkish", area: "Addison/Belt Line", note: "OG location, consistently packed", price: 2, rating: 4.7, reviews: 2156, url: "https://seldadallas.com", mapsQuery: "Selda+Mediterranean+Dallas+TX", recommended: true, isNew: false, lat: 32.9536, lng: -96.8029 },
  { name: "Darna Mediterranean", city: "Dallas", category: "Lebanese", area: "Legacy West, Plano", note: "Lebanese plates, lamb cigars, fresh pita", price: 1, rating: 4.6, reviews: 2102, url: "https://darnadallas.com", mapsQuery: "Darna+Mediterranean+Plano+TX", recommended: true, isNew: false, lat: 33.0738, lng: -96.8235 },
  { name: "Khashoka Middle Eastern Cuisine", city: "Dallas", category: "Jordanian", area: "Richardson", note: "Mansaf, incredible bread, hidden gem", price: 2, rating: 4.8, reviews: 1826, url: null, mapsQuery: "Khashoka+Middle+Eastern+Richardson+TX", recommended: true, isNew: false, lat: 32.9482, lng: -96.7298 },
  { name: "WAVA Halal Grill", city: "Dallas", category: "General Med", area: "Greenville Ave", note: "Halal plates, gyro, falafel, open until 3AM", price: 1, rating: 4.5, reviews: 1808, url: null, mapsQuery: "WAVA+Halal+Grill+Dallas+TX", recommended: false, isNew: false, lat: 32.8408, lng: -96.7616 },
  { name: "Samad Cafe", city: "Dallas", category: "Persian", area: "Love Field", note: "38-year institution, lamb shank, lunch only", price: 2, rating: 4.9, reviews: 1686, url: null, mapsQuery: "Samad+Cafe+Dallas+TX", recommended: true, isNew: false, lat: 32.8478, lng: -96.8512 },
  { name: "Sketches of Spain", city: "Dallas", category: "Spanish", area: "Oak Cliff", note: "Best Spanish in Dallas, authentic paella, pulpo", price: 2, rating: 4.7, reviews: 1627, url: null, mapsQuery: "Sketches+of+Spain+Dallas+TX", recommended: true, isNew: false, lat: 32.7312, lng: -96.8428 },
  { name: "Cafe Madrid", city: "Dallas", category: "Spanish", area: "Knox-Henderson", note: "Flamenco dancers, tapas, paella", price: 2, rating: 4.5, reviews: 1391, url: null, mapsQuery: "Cafe+Madrid+Dallas+TX", recommended: true, isNew: false, lat: 32.8218, lng: -96.7852 },
  { name: "Open Sesame", city: "Dallas", category: "Lebanese", area: "Oak Lawn", note: "Shawarma, kebabs, hummus, baba ganoush", price: 2, rating: 4.5, reviews: 1376, url: null, mapsQuery: "Open+Sesame+Lebanese+Grill+Dallas+TX", recommended: true, isNew: false, lat: 32.8158, lng: -96.8105 },
  { name: "Baboush", city: "Dallas", category: "Lebanese", area: "McKinney Ave", note: "Lebanese-Moroccan, walkable from Uptown", price: 2, rating: 4.4, reviews: 1359, url: "https://baboushrestaurant.com", mapsQuery: "Baboush+Dallas+TX", recommended: true, isNew: false, lat: 32.8028, lng: -96.7982 },
  { name: "Kasra Restaurant", city: "Dallas", category: "Persian", area: "Richardson", note: "Ghormeh sabzi, tahdig, fesenjan", price: 2, rating: 4.3, reviews: 1329, url: null, mapsQuery: "Kasra+Restaurant+Richardson+TX", recommended: true, isNew: false, lat: 32.9486, lng: -96.7290 },
  { name: "Shiraz Mediterranean Grill", city: "Dallas", category: "Persian", area: "Preston Rd", note: "Persian kabobs, solid rice", price: 2, rating: 4.1, reviews: 1309, url: null, mapsQuery: "Shiraz+Mediterranean+Grill+Dallas+TX", recommended: true, isNew: false, lat: 32.8895, lng: -96.7718 },
  { name: "Shahrzad Mediterranean", city: "Dallas", category: "Persian", area: "Richardson", note: "Persian buffet, market and grill", price: 2, rating: 4.0, reviews: 1261, url: null, mapsQuery: "Shahrzad+Mediterranean+Market+Richardson+TX", recommended: false, isNew: false, lat: 32.9482, lng: -96.7288 },
  { name: "Arash Persian Grill", city: "Dallas", category: "Persian", area: "Richardson", note: "Koobideh, branzino, free tea at the end", price: 2, rating: 4.7, reviews: 1198, url: "https://arashpersian.com", mapsQuery: "Arash+Persian+Grill+Richardson+TX", recommended: true, isNew: false, lat: 32.8895, lng: -96.7717 },
  { name: "Noorsha Cafe & Bakery", city: "Dallas", category: "Turkish", area: "Richardson", note: "Lahmacun, borek, dumplings, free chai", price: 2, rating: 4.8, reviews: 1213, url: null, mapsQuery: "Noorsha+Cafe+Bakery+Richardson+TX", recommended: true, isNew: false, lat: 32.9486, lng: -96.7299 },
  { name: "Barcelona Wine Bar", city: "Dallas", category: "Spanish", area: "Lower Greenville", note: "Tapas, great wine list, shrimp, pork belly", price: 2, rating: 4.5, reviews: 1286, url: "https://barcelonawinebar.com", mapsQuery: "Barcelona+Wine+Bar+Dallas+TX", recommended: true, isNew: false, lat: 32.8408, lng: -96.7606 },
  { name: "Si Tapas", city: "Dallas", category: "Spanish", area: "Allen St, Uptown", note: "Converted house, 20+ years, near Uptown", price: 2, rating: 4.3, reviews: 1188, url: null, mapsQuery: "Si+Tapas+Dallas+TX", recommended: true, isNew: false, lat: 32.8025, lng: -96.7972 },
  { name: "Master Kabob", city: "Dallas", category: "Persian", area: "Arlington", note: "4.9 stars, huge portions, perfect kabobs", price: 2, rating: 4.9, reviews: 1040, url: null, mapsQuery: "Master+Kabob+Arlington+TX", recommended: false, isNew: false, lat: 32.7357, lng: -97.1081 },
  { name: "Luna Grill", city: "Dallas", category: "General Med", area: "Walnut Hill", note: "Fast casual, flame-grilled kabobs, clean ingredients", price: 2, rating: 4.6, reviews: 1081, url: "https://lunagrill.com", mapsQuery: "Luna+Grill+Dallas+TX", recommended: true, isNew: false, lat: 32.8672, lng: -96.8092 },
  { name: "Ephesus Mediterranean Grill", city: "Dallas", category: "Turkish", area: "North Dallas", note: "Adana, lamb chops, branzino", price: 2, rating: 4.6, reviews: 872, url: null, mapsQuery: "Ephesus+Mediterranean+Grill+Dallas+TX", recommended: false, isNew: false, lat: 32.9128, lng: -96.8092 },
  { name: "Sahara Mediterranean", city: "Dallas", category: "Persian", area: "Dallas", note: "Persian/Med plates, chicken kubideh", price: 2, rating: 4.2, reviews: 847, url: null, mapsQuery: "Sahara+Mediterranean+Restaurant+Dallas+TX", recommended: false, isNew: false, lat: 32.8672, lng: -96.8098 },
  { name: "Ziziki's", city: "Dallas", category: "Greek", area: "Knox-Henderson", note: "Best gyro in Dallas, great tzatziki", price: 2, rating: 4.6, reviews: 786, url: "https://zizikis.com", mapsQuery: "Zizikis+Dallas+TX", recommended: true, isNew: false, lat: 32.8218, lng: -96.7855 },
  { name: "Phoenician Resto Cafe", city: "Dallas", category: "Lebanese", area: "North Dallas", note: "Lebanese/Greek mixed grill, falafel", price: 2, rating: 4.6, reviews: 977, url: null, mapsQuery: "Phoenician+Resto+Cafe+Dallas+TX", recommended: false, isNew: false, lat: 32.8895, lng: -96.7715 },
  { name: "Kabobzi Mediterranean Grill", city: "Dallas", category: "Lebanese", area: "North Dallas", note: "Shawarma, gyro bowl, warm pita", price: 2, rating: 4.5, reviews: 700, url: null, mapsQuery: "Kabobzi+Mediterranean+Grill+Dallas+TX", recommended: false, isNew: false, lat: 32.8895, lng: -96.7718 },
  { name: "Kostas Cafe", city: "Dallas", category: "Greek", area: "Greenville Ave", note: "Best lamb chops, dolmas, spanakopita", price: 2, rating: 4.7, reviews: 624, url: "https://kostascafe.com", mapsQuery: "Kostas+Cafe+Dallas+TX", recommended: true, isNew: false, lat: 32.8328, lng: -96.7608 },
  { name: "Chefika", city: "Dallas", category: "Turkish", area: "North Dallas", note: "Closest to MezzeMe in Dallas, mezze platters, kofte", price: 2, rating: 4.7, reviews: 628, url: "https://chefikadallas.com", mapsQuery: "Chefika+Dallas+TX", recommended: true, isNew: false, lat: 32.8895, lng: -96.7720 },
  { name: "Cafe Izmir", city: "Dallas", category: "General Med", area: "Lower Greenville", note: "Med tapas, BYOB, 25-year Dallas institution", price: 2, rating: 4.4, reviews: 629, url: null, mapsQuery: "Cafe+Izmir+Dallas+TX", recommended: true, isNew: false, lat: 32.8408, lng: -96.7609 },
  { name: "Zatar Lebanese Tapas & Bar", city: "Dallas", category: "Lebanese", area: "Deep Ellum", note: "Lebanese small plates, hookah, evening spot", price: 2, rating: 4.3, reviews: 926, url: null, mapsQuery: "Zatar+Lebanese+Tapas+Bar+Dallas+TX", recommended: false, isNew: false, lat: 32.7835, lng: -96.7718 },
  { name: "Elia Greek Tavern", city: "Dallas", category: "Greek", area: "Bishop Arts", note: "Highest rated Greek in Dallas, souvlaki, cocktails", price: 2, rating: 4.8, reviews: 495, url: null, mapsQuery: "Elia+Greek+Tavern+Dallas+TX", recommended: true, isNew: false, lat: 32.7482, lng: -96.8385 },
  { name: "Food From Galilee", city: "Dallas", category: "Israeli", area: "Snider Plaza", note: "Only dedicated Israeli spot in Dallas, falafel, lamb gyro", price: 1, rating: 4.6, reviews: 431, url: null, mapsQuery: "Food+From+Galilee+Dallas+TX", recommended: true, isNew: false, lat: 32.8558, lng: -96.7980 },
  { name: "Aderet", city: "Dallas", category: "Israeli", area: "Preston Road", note: "Authentic Israeli, chicken schnitzel, baba ganoush", price: 2, rating: 4.6, reviews: 434, url: null, mapsQuery: "Aderet+Dallas+TX", recommended: true, isNew: false, lat: 32.8895, lng: -96.7712 },
  { name: "Sevan G&G Cafe", city: "Dallas", category: "Greek", area: "Lower Greenville", note: "Tiny BYOB hole in the wall, everything cooked to order", price: 2, rating: 4.7, reviews: 345, url: null, mapsQuery: "Sevan+G+G+Cafe+Dallas+TX", recommended: true, isNew: false, lat: 32.8328, lng: -96.7612 },
  { name: "Little Persia", city: "Dallas", category: "Persian", area: "Plano", note: "Huge portions, koobideh, chicken kabob, great value", price: 2, rating: 4.8, reviews: 314, url: null, mapsQuery: "Little+Persia+Plano+TX", recommended: true, isNew: false, lat: 33.0198, lng: -96.6989 },
  { name: "Selda Las Colinas", city: "Dallas", category: "Turkish", area: "Irving", note: "Highest rated Selda, lamb chops, Ali Nazik", price: 2, rating: 4.9, reviews: 391, url: "https://seldadallas.com", mapsQuery: "Selda+Las+Colinas+Irving+TX", recommended: true, isNew: false, lat: 32.8582, lng: -96.9472 },
  { name: "Greek Isles Grill & Taverna", city: "Dallas", category: "Greek", area: "North Dallas", note: "Family-owned, saganaki, lamb chops", price: 2, rating: 4.6, reviews: 261, url: null, mapsQuery: "Greek+Isles+Grill+Taverna+Dallas+TX", recommended: true, isNew: false, lat: 32.8806, lng: -96.7730 },
  { name: "Koshary Time", city: "Dallas", category: "Egyptian", area: "Garland", note: "Food truck, koshary bowls, perfect rating", price: 1, rating: 5.0, reviews: 191, url: null, mapsQuery: "Koshary+Time+Garland+TX", recommended: true, isNew: false, lat: 32.9126, lng: -96.6389 },
  // AUSTIN
  { name: "Arpeggio Grill", city: "Austin", category: "Greek", area: "Airport Blvd", note: "Greek/Med, gyro lunch special, very affordable", price: 1, rating: 4.4, reviews: 2990, url: null, mapsQuery: "Arpeggio+Grill+Austin+TX", recommended: false, isNew: false, lat: 30.2962, lng: -97.6982 },
  { name: "MezzeMe", city: "Austin", category: "Turkish", area: "The Triangle", note: "Turkish kebabs, Adana, pide, baklava — original inspiration", price: 2, rating: 4.6, reviews: 2100, url: "http://www.mezzeme.com", mapsQuery: "MezzeMe+Austin+TX", recommended: true, isNew: false, lat: 30.3154, lng: -97.7332 },
  { name: "Almarah Grill", city: "Austin", category: "Lebanese", area: "620/NW Austin", note: "Lebanese/Med, mixed grill, fresh pita, open late", price: 2, rating: 4.4, reviews: 1057, url: "https://www.almarahgrill.com", mapsQuery: "Almarah+Grill+Austin+TX", recommended: true, isNew: false, lat: 30.4609, lng: -97.8170 },
  { name: "Kebabalicious", city: "Austin", category: "Lebanese", area: "East 7th", note: "Kebab wraps and bowls, great falafel, Chipotle price", price: 1, rating: 4.5, reviews: 1425, url: "http://www.kebabalicious.com", mapsQuery: "Kebabalicious+Austin+TX", recommended: false, isNew: false, lat: 30.2645, lng: -97.7283 },
  { name: "TX Shawarma", city: "Austin", category: "Lebanese", area: "South Austin", note: "Food truck, chicken/beef shawarma, crispy gyro edges", price: 1, rating: 4.7, reviews: 598, url: "http://txshawarma.com", mapsQuery: "TX+Shawarma+Austin+TX", recommended: false, isNew: false, lat: 30.2444, lng: -97.7580 },
  { name: "Pita Shack Grill", city: "Austin", category: "Lebanese", area: "Burnet Rd", note: "Huge portions, free lentil soup, mix grill, lamb", price: 2, rating: 4.8, reviews: 515, url: "https://pitashackaustin.toast.site", mapsQuery: "Pita+Shack+Grill+Austin+TX", recommended: true, isNew: false, lat: 30.3954, lng: -97.7198 },
  { name: "Abo Youssef Mediterranean Food", city: "Austin", category: "Lebanese", area: "East Austin", note: "Shawarma, gyro plates, free baklava, owner is a gem", price: 1, rating: 4.8, reviews: 562, url: null, mapsQuery: "Abo+Youssef+Mediterranean+Austin+TX", recommended: true, isNew: false, lat: 30.2840, lng: -97.7200 },
  { name: "Roya", city: "Austin", category: "Persian", area: "Shoal Creek", note: "Upscale Persian, ghormeh sabzi, kebabs, refined", price: 3, rating: 4.7, reviews: 338, url: "https://royaaustin.com", mapsQuery: "Roya+Austin+TX", recommended: true, isNew: false, lat: 30.3608, lng: -97.7415 },
]
